export const INTEGER_START = 'i' // 'i'
export const STRING_DELIMITER = ':' // ':'
export const DICTIONARY_START = 'd' // 'd'
export const LIST_START = 'l' // 'l'
export const END_OF_TYPE = 'e' // 'e'
